### ISSUE TITLE
Small bug in heuristics.py?

### ISSUE THREAD

**Issue by YingX97** [fabilab/scquill#1]
Hi Fabio,
The q = scquill.Compressor(...) does work for some files. I think there is a small bug in this file:
**scquill/utils/heuristics.py**
line 24 should be Xe = np.expm1(adata.X)

<img width="375" alt="Screen Shot 2024-05-31 at 3 01 34 pm" src="https://github.com/fabilab/scquill/assets/98261770/62584f89-6d6f-460d-9db8-c79287fed1d4">

**Comment by iosonofabio** [comment]
fixed in c834ddf..ad1fc5a
